= SmallRye Health in Quarkus
ifndef::imagesdir[:imagesdir: images]
:icons: font
:experimental:
:sectnums:
:toc:
:toclevels: 5
:experimental:

== Einführung

=== Was ist Health Monitoring?
[quote]
Unter Health Monitoring versteht man den Prozess der Überprüfung des Zustands einer Anwendung,
um sicherzustellen, dass sie ordnungsgemäß und zuverlässig funktioniert.
Dabei wird die Fähigkeit der Anwendung verfolgt, zu starten, auszuführen und Datenverkehr effektiv zu verarbeiten.
Health Monitoring ist ein Eckpfeiler des modernen Anwendungsmanagements,
insbesondere in verteilten und Cloud-nativen Umgebungen.

=== Warum ist Health Monitoring wichtig?
* *Reliability* (Zuverlässigkeit): Erkennt Probleme frühzeitig, um Ausfallzeiten zu verhindern.
* *Scalability* (Skalierbarkeit): Stellt sicher, dass Systeme skaliert werden können, ohne dass kritische Komponenten beschädigt werden.
* *Integration*: Funktioniert mit Tools wie Kubernetes, um die Wiederherstellung zu automatisieren und die Ressourcennutzung zu verbessern. -> *Probes*

=== Eclipse MicroProfile Health
* Spezifikation im MicroProfile-Ökosystem, bietet standardisierte Möglichkeit zur Implementierung von Health-Checks

=== SmallRye Health
* konkrete Implementierung der Eclipse MicroProfile Health API
* von Quarkus verwendet

== Praxisbeispiel: SmallRye Health in Quarkus

=== Standard Health Checks ausprobieren

==== Maven-Projekt erstellen

[%collapsible]
====
[source, bash]
----
mvn io.quarkus.platform:quarkus-maven-plugin:3.18.1:create \
    -DprojectGroupId==at.htlleonding \
    -DprojectArtifactId==microprofile-health-demo \
    -Dextensions=='smallrye-health' \
    -DnoCode
cd microprofile-health-demo
----
====

==== Oder Extension zu bestehendem Projekt hinzufügen

[%collapsible]
====
.Maven-Wrapper
[source, bash]
----
./mvnw quarkus:add-extension -Dextensions=='smallrye-health'
----

oder

.pom.xml
[source, xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-smallrye-health</artifactId>
</dependency>
----
====

==== Maven-Projekt starten

[source, bash]
----
./mvnw clean quarkus:dev
----

==== Standard-Endpoints

Der Import der `smallrye-health` Extension stellt direkt 3 REST-Endpunkte bereit:

===== Liveness (Live)
* `GET /q/health/live`
* Zeigt an, dass die Anwendung ausgeführt wird und kein kritischer Fehler aufgetreten ist, der einen Neustart erforderlich macht.
* Falls die JVM oder der Container abstürzt oder sich in einem fehlerhaften Zustand befindet, schlägt der Liveness-Check fehl.

===== Readiness (Ready)
* `GET /q/health/ready`
* Zeigt an, dass die Anwendung zur Bearbeitung von Anfragen bereit und voll funktionsfähig ist.
* Falls Quarkus eine Abhängigkeit erkennt (z. B. Datenbank oder externe API), kann es automatisch bestimmen, dass die Anwendung nicht bereit ist, falls diese Abhängigkeit nicht verfügbar ist.

===== Started
* `GET /q/health/started`
* Zeigt an, ob der vollständige Startprozess abgeschlossen ist.
* Dies geschieht, nachdem alle Startup-Beans und StartupEvent-Listener vollständig ausgeführt wurden.

TIP: Mit `GET /q/health` werden alle Health-Checks angezeigt. Du kannst diese Endpoints nun ausprobieren.

Anzeige aller Checks:
[%collapsible]
====

.`/q/health`
[source, json]
----
{
    "status": "UP", <1>
    "checks": [ <2>
    ]
}
----

.`/q/health/live`
[source, json]
----
{
    "status": "UP", <1>
    "checks": [ <2>
    ]
}
----

.`/q/health/ready`
[source, json]
----
{
    "status": "UP", <1>
    "checks": [ <2>
    ]
}
----

.`/q/health/started`
[source, json]
----
{
    "status": "UP", <1>
    "checks": [ <2>
    ]
}
----
1. `status` gibt an, ob alle Health-Checks erfolgreich waren.
2. `checks` ist ein Array von individuellen Health-Checks (dazu später mehr).

====

=== Automatischer Health-Check für JDBC-Verbindungen

NOTE: Wenn wir zu unserem Projekt eine JDBC-Datasource hinzufügen, wird automatisch ein Health Check (Readiness) erstellt, der die Verbindung zur Datenbank prüft. Hier wird dies mit einer PostgreSQL-DB demonstriert.

Siehe auch: link:quarkus-add-jdbc-postgres-source[Quarkus: JDBC Datasource hinzufügen - mit PostgreSQL als Beispiel]

*Nach der Konfiguration einer JDBC-Datasource ist bei den Readiness-Checks ist nun auch sichtbar, ob die Datenbank-Verbindung aufrecht ist:*

[%collapsible]
====
.`/q/health/ready`
[source, json]
----
{
    "status": "UP",
    "checks": [
        {
            "name": "Database connections health check",
            "status": "UP",
            "data": {
                "<default>": "UP"
            }
        }
    ]
}
----
====

*Stoppe nun die Datenbank und sieh dir die Readiness-Checks erneut an:*

[%collapsible]
====
.`/q/health/ready`
[source, json]
----
{
    "status": "DOWN",
    "checks": [
        {
            "name": "Database connections health check",
            "status": "DOWN",
            "data": {
                "<default>": "Unable to execute the validation check for the default DataSource: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections."
            }
        }
    ]
}
----
====

=== Eigene Health-Checks erstellen

Es ist auch möglich in Quarkus eigene Health-Checks zu erstellen.
Dabei implementiert deine Health-Check-Klasse das Interface `HealthCheck` und trägt die `@Liveness`, `@Readiness` oder `@Startup` Annotation - je nach dem welche Art von Health-Check gefordert ist.

==== Beispiel mit einer Readiness Health-Check Prozedur

[source, java]
----
package at.htlleonding.healthchecks;

import jakarta.enterprise.context.ApplicationScoped;
import org.eclipse.microprofile.health.HealthCheck;
import org.eclipse.microprofile.health.HealthCheckResponse;
import org.eclipse.microprofile.health.Readiness;

import java.util.Random;

@Readiness //<1>
@ApplicationScoped //<2>
public class CustomReadinessCheck implements HealthCheck { //<3>
    @Override
    public HealthCheckResponse call() { //<4>
        boolean b = new Random().nextBoolean(); //<5>

        if(b) {
            return HealthCheckResponse.up("custom readiness check"); //<6>
        } else {
            return HealthCheckResponse.down("custom readiness check"); //<7>
        }
    }
}

----
1. Die Klasse soll einen Readiness-Check durchführen, daher die Annotation `@Readiness`.
2. `@ApplicationScoped` wird empfohlen, damit nur eine Instanz für alle Requests verwendet wird.
3. Die Klasse implementiert das Interface `HealthCheck`
4. `call()` führt den Check durch und liefert ein `HealthCheckResponse` zurück
5. Hier wird durch einen zufälligen Boolean das Ergebnis des Health-Checks simuliert. Dies ist dann in einem Produktivsystem durch eine sinnvolle Methode zu erstzen (z.B. _Ist die DB-Verbindung aufrecht?_)
6. Im positiven Falle wird `HealthCheckResponse.up` mit dem Namen des Health-Checks zurückgegeben.
7. Im negativen Falle wird `HealthCheckResponse.down` mit dem Namen des Health-Checks zurückgegeben.

=== SmallRye Health für Probes in Kubernetes verwenden

[quote]
Kubernetes nutzt **Probes** zur Überwachung von Containern: **Liveness** für Neustarts, **Readiness** für die Traffic-Steuerung und **Startup** für lange Startprozesse. **SmallRye Health** stellt dafür die Endpunkte `/q/health/live`, `/q/health/ready` und `/q/health/started` bereit, die Kubernetes direkt nutzen kann, um den Zustand der Anwendung automatisch zu verwalten.

==== Docker Image bauen

Siehe auch: link:quarkus-build-docker-image[GitHub Actions: Docker Image einer Quarkus Applikation bauen]

==== LeoCloud CLI & kubectl installieren

Siehe auch: link:https://cloud.htl-leonding.ac.at/html/user-manual.html[LeoCloud User Manual]

==== LeoCloud Dashboard starten

Siehe auch: link:https://cloud.htl-leonding.ac.at/html/user-manual.html#_dashboard[LeoCloud User Manual > Dashboard]

==== Credentials für GitHub Container Registry einpflegen (falls Image privat)

[source, bash]
----
kubectl create secret docker-registry regcred \
  --docker-server=ghcr.io \
  --docker-username=YOUR_GITHUB_USERNAME \
  --docker-password=YOUR_GITHUB_PAT \ #<1>
  --docker-email=YOUR_EMAIL

----
1. Hier ist ein Token erforderlich, die einfache Eingabe des Passwortes funktioniert nicht

==== Konfigurationsdateien erstellen

*1.* PVC, Service & Deployment für die *PostgreSQL-Datenbank*

[%collapsible]
====
.k8s/postgres.yaml
[source, yaml]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: app
            - name: POSTGRES_PASSWORD
              value: app
            - name: POSTGRES_DB
              value: db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - app
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - app
            initialDelaySeconds: 3
            periodSeconds: 5
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

----
====

*2.* Deployment & Service für die *Quarkus-Applikation*

[%collapsible]
====
.k8s/quarkus-app.yaml
[source, yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      imagePullSecrets:
        - name: regcred  #<1>
      containers:
        - name: quarkus-app
          image: ghcr.io/2425-5bhif-wmc/01-referate-marksuus/mp-health-demo:latest #<2>
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://postgres:5432/db
            - name: QUARKUS_DATASOURCE_USERNAME
              value: app
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: app
          livenessProbe: #<3>
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 5    # Warte 5 Sekunden nach dem Start, bevor die erste Prüfung erfolgt
            periodSeconds: 10         # Alle 10 Sekunden wird die Probe wiederholt
            timeoutSeconds: 2         # Die App hat 2 Sekunden Zeit zu antworten, bevor sie als "failed" gilt
            failureThreshold: 3       # Nach 3 Fehlschlägen startet Kubernetes den Container neu
          readinessProbe: #<4>
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 3    # Bereits nach 3 Sekunden prüfen, ob die App Traffic verarbeiten kann
            periodSeconds: 5         # Alle 5 Sekunden wird die Probe wiederholt
            timeoutSeconds: 2        # Die App hat 2 Sekunden Zeit zu antworten
            failureThreshold: 2      # Nach 2 Fehlschlägen wird der Container aus dem Load Balancer entfernt
          startupProbe: #<5>
            httpGet:
              path: /q/health/started
              port: 8080
            initialDelaySeconds: 0    # Sofort nach dem Start prüfen
            periodSeconds: 5         # Alle 5 Sekunden wird geprüft, ob die App vollständig gestartet ist
            timeoutSeconds: 3        # Die App hat 3 Sekunden Zeit zu antworten
            failureThreshold: 30     # Erlaubt 30 Fehlschläge = maximal 150 Sekunden (30 * 5s), bevor der Container neu gestartet wird
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-service
spec:
  selector:
    app: quarkus
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
----
1. Dies wird bei nicht-öffentlichen Images benötigt. Hierbei greifen wir auf das vorhin angelegt Secret zu.
2. Image-Name mit deinem ersetzen.
3. Konfiguration der Liveness-Probe. Als Endpunkt wird `/q/health/live` verwendet.
4. Konfiguration der Readiness-Probe. Als Endpunkt wird `/q/health/ready` verwendet.
5. Konfiguration der Startup-Probe. Als Endpunkt wird `/q/health/started` verwendet.

NOTE: *initialDelaySeconds*: Gibt an, wie lange Kubernetes nach dem Start des Containers wartet, bevor es die erste Probe durchführt.

NOTE: *periodSeconds*: Gibt an, wie oft (in Sekunden) Kubernetes die Probe wiederholt.

NOTE: *timeoutSeconds*: Gibt an, wie lange Kubernetes auf eine Antwort wartet, bevor die Probe als fehlgeschlagen gilt.
====

*3.* *Ingress* für die Quarkus-Applikation

[%collapsible]
====
.k8s/quarkus-ingress.yaml
[source, yaml]
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quarkus-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: if200156.cloud.htl-leonding.ac.at #<1>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quarkus-service
                port:
                  number: 8080
----
1. Mit deinem Namespace ersetzen
====

==== Resourcen erstellen

.im Verzeichnis der Konfigurationsdateien (k8s)
[source, bash]
----
kubectl apply -f postgres.yaml
kubectl apply -f quarkus-app.yaml
kubectl apply -f quarkus-ingress.yaml
----

=== *Was macht Kubernetes nun, wenn eine der Probes fehlschlägt?*

[options="header"]
|===
| Probe         | Prüft was?                        | Verhalten bei Fehlschlag
| Liveness      | Läuft die App noch oder ist sie abgestürzt? | *Container wird als "unhealthy" markiert.* Nach `failureThreshold` Fehlschlägen startet Kubernetes den Container neu.
| Readiness     | Kann die App Anfragen verarbeiten? | *Container bleibt am Leben, aber erhält keinen Traffic mehr.* Sobald die Probe wieder erfolgreich ist, wird der Container wieder in den Load Balancer aufgenommen.
| Startup       | Ist die App noch im Startprozess? | *Solange die Startup Probe fehlschlägt, ignoriert Kubernetes Liveness und Readiness.* Erst wenn die Startup Probe erfolgreich ist, starten die anderen Probes.
|===


== Begriffsklärung

* Load Balancer: Der Load Balancer ist eine Kubernetes-Komponente, die den eingehenden Traffic auf mehrere laufende Pods verteilt. Dadurch werden die Last und Anfragen optimal verteilt, um eine hohe Verfügbarkeit und Skalierbarkeit sicherzustellen.

== Quellen und Links
* https://quarkus.io/guides/smallrye-health[quarkus.io: SmallRye Health]
* https://github.com/smallrye/smallrye-health[GitHub: SmallRye Health]
* https://github.com/eclipse/microprofile-health/[GitHub: Eclipse MicroProfile Health]
* https://cloud.htl-leonding.ac.at/html/user-manual.html[C. Aberger: LeoCloud User Manual]
* https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/[kubernetes.io: Configure Liveness, Readiness and Startup Probes]